import { style, styleVariants } from '@vanilla-extract/css';
import { animation, color, variables } from '~/kernel/styles';

const background = style({
  position: 'absolute',
  top: 0,
  left: 0,
  right: 0,
  bottom: 0,
  width: variables.breakpoint.lg,
  height: variables.breakpoint.lg,
  margin: '0 auto',
});

const vertical = styleVariants({
  one: {
    position: 'absolute',
    top: 0,
    left: '10%',
    width: '1px',
    height: '100%',
    background: `linear-gradient(0deg, rgba(0,0,0,0) 0%, ${color.semantic.neutral[925]} 50%,  rgba(0,0,0,0) 100%);`,

    animation: `${animation.fadeIn} 2s ${animation.easing.snappy} forwards`,
    animationDelay: '1s',
    animationFillMode: 'backwards',
    WebkitAnimationFillMode: 'backwards',
  },
  two: {
    position: 'absolute',
    top: 0,
    left: '20%',
    width: '1px',
    height: '100%',
    background: `linear-gradient(0deg, rgba(0,0,0,0) 0%, ${color.semantic.neutral[900]} 50%,  rgba(0,0,0,0) 100%);`,

    animation: `${animation.fadeIn} 2s ${animation.easing.snappy} forwards`,
    animationDelay: '1s',
    animationFillMode: 'backwards',
    WebkitAnimationFillMode: 'backwards',
  },
  three: {
    position: 'absolute',
    top: 0,
    left: '30%',
    width: '1px',
    height: '100%',
    background: `linear-gradient(0deg, rgba(0,0,0,0) 0%, ${color.semantic.neutral[900]} 50%,  rgba(0,0,0,0) 100%);`,

    animation: `${animation.fadeIn} 2s ${animation.easing.snappy} forwards`,
    animationDelay: '1s',
    animationFillMode: 'backwards',
    WebkitAnimationFillMode: 'backwards',
  },
  four: {
    position: 'absolute',
    top: 0,
    left: '40%',
    width: '1px',
    height: '100%',
    background: `linear-gradient(0deg, rgba(0,0,0,0) 0%, ${color.semantic.neutral[900]} 50%,  rgba(0,0,0,0) 100%);`,

    animation: `${animation.fadeIn} 2s ${animation.easing.snappy} forwards`,
    animationDelay: '1s',
    animationFillMode: 'backwards',
    WebkitAnimationFillMode: 'backwards',
  },
  five: {
    position: 'absolute',
    top: 0,
    left: '50%',
    width: '1px',
    height: '100%',
    background: `linear-gradient(0deg, rgba(0,0,0,0) 0%, ${color.semantic.neutral[900]} 50%,  rgba(0,0,0,0) 100%);`,

    animation: `${animation.fadeIn} 2s ${animation.easing.snappy} forwards`,
    animationDelay: '1s',
    animationFillMode: 'backwards',
    WebkitAnimationFillMode: 'backwards',
  },
  six: {
    position: 'absolute',
    top: 0,
    left: '60%',
    width: '1px',
    height: '100%',
    background: `linear-gradient(0deg, rgba(0,0,0,0) 0%, ${color.semantic.neutral[900]} 50%,  rgba(0,0,0,0) 100%);`,

    animation: `${animation.fadeIn} 2s ${animation.easing.snappy} forwards`,
    animationDelay: '1s',
    animationFillMode: 'backwards',
    WebkitAnimationFillMode: 'backwards',
  },
  seven: {
    position: 'absolute',
    top: 0,
    left: '70%',
    width: '1px',
    height: '100%',
    background: `linear-gradient(0deg, rgba(0,0,0,0) 0%, ${color.semantic.neutral[900]} 50%,  rgba(0,0,0,0) 100%);`,

    animation: `${animation.fadeIn} 2s ${animation.easing.snappy} forwards`,
    animationDelay: '1s',
    animationFillMode: 'backwards',
    WebkitAnimationFillMode: 'backwards',
  },
  eight: {
    position: 'absolute',
    top: 0,
    left: '80%',
    width: '1px',
    height: '100%',
    background: `linear-gradient(0deg, rgba(0,0,0,0) 0%, ${color.semantic.neutral[900]} 50%,  rgba(0,0,0,0) 100%);`,

    animation: `${animation.fadeIn} 2s ${animation.easing.snappy} forwards`,
    animationDelay: '1s',
    animationFillMode: 'backwards',
    WebkitAnimationFillMode: 'backwards',
  },
  nine: {
    position: 'absolute',
    top: 0,
    left: '90%',
    width: '1px',
    height: '100%',
    background: `linear-gradient(0deg, rgba(0,0,0,0) 0%, ${color.semantic.neutral[925]} 50%,  rgba(0,0,0,0) 100%);`,

    animation: `${animation.fadeIn} 2s ${animation.easing.snappy} forwards`,
    animationDelay: '1s',
    animationFillMode: 'backwards',
    WebkitAnimationFillMode: 'backwards',
  },
});

const horizontal = styleVariants({
  one: {
    position: 'absolute',
    top: '10%',
    left: 0,
    width: '100%',
    height: '1px',
    background: `linear-gradient(90deg, rgba(0,0,0,0) 0%, ${color.semantic.neutral[925]} 20%, ${color.semantic.neutral[925]} 80%, rgba(0,0,0,0) 100%);`,

    animation: `${animation.fadeIn} 2s ${animation.easing.snappy} forwards`,
    animationDelay: '1s',
    animationFillMode: 'backwards',
    WebkitAnimationFillMode: 'backwards',
  },
  two: {
    position: 'absolute',
    top: '20%',
    left: 0,
    width: '100%',
    height: '1px',
    background: `linear-gradient(90deg, rgba(0,0,0,0) 0%, ${color.semantic.neutral[900]} 20%, ${color.semantic.neutral[900]} 80%, rgba(0,0,0,0) 100%);`,

    animation: `${animation.fadeIn} 2s ${animation.easing.snappy} forwards`,
    animationDelay: '1s',
    animationFillMode: 'backwards',
    WebkitAnimationFillMode: 'backwards',
  },
  three: {
    position: 'absolute',
    top: '30%',
    left: 0,
    width: '100%',
    height: '1px',
    background: `linear-gradient(90deg, rgba(0,0,0,0) 0%, ${color.semantic.neutral[900]} 20%, ${color.semantic.neutral[900]} 80%, rgba(0,0,0,0) 100%);`,

    animation: `${animation.fadeIn} 2s ${animation.easing.snappy} forwards`,
    animationDelay: '1s',
    animationFillMode: 'backwards',
    WebkitAnimationFillMode: 'backwards',
  },
  four: {
    position: 'absolute',
    top: '40%',
    left: 0,
    width: '100%',
    height: '1px',
    background: `linear-gradient(90deg, rgba(0,0,0,0) 0%, ${color.semantic.neutral[900]} 20%, ${color.semantic.neutral[900]} 80%, rgba(0,0,0,0) 100%);`,

    animation: `${animation.fadeIn} 2s ${animation.easing.snappy} forwards`,
    animationDelay: '1s',
    animationFillMode: 'backwards',
    WebkitAnimationFillMode: 'backwards',
  },
  five: {
    position: 'absolute',
    top: '50%',
    left: 0,
    width: '100%',
    height: '1px',
    background: `linear-gradient(90deg, rgba(0,0,0,0) 0%, ${color.semantic.neutral[900]} 20%, ${color.semantic.neutral[900]} 80%, rgba(0,0,0,0) 100%);`,

    animation: `${animation.fadeIn} 2s ${animation.easing.snappy} forwards`,
    animationDelay: '1s',
    animationFillMode: 'backwards',
    WebkitAnimationFillMode: 'backwards',
  },
  six: {
    position: 'absolute',
    top: '60%',
    left: 0,
    width: '100%',
    height: '1px',
    background: `linear-gradient(90deg, rgba(0,0,0,0) 0%, ${color.semantic.neutral[900]} 20%, ${color.semantic.neutral[900]} 80%, rgba(0,0,0,0) 100%);`,

    animation: `${animation.fadeIn} 2s ${animation.easing.snappy} forwards`,
    animationDelay: '1s',
    animationFillMode: 'backwards',
    WebkitAnimationFillMode: 'backwards',
  },
  seven: {
    position: 'absolute',
    top: '70%',
    left: 0,
    width: '100%',
    height: '1px',
    background: `linear-gradient(90deg, rgba(0,0,0,0) 0%, ${color.semantic.neutral[900]} 20%, ${color.semantic.neutral[900]} 80%, rgba(0,0,0,0) 100%);`,

    animation: `${animation.fadeIn} 2s ${animation.easing.snappy} forwards`,
    animationDelay: '1s',
    animationFillMode: 'backwards',
    WebkitAnimationFillMode: 'backwards',
  },
  eight: {
    position: 'absolute',
    top: '80%',
    left: 0,
    width: '100%',
    height: '1px',
    background: `linear-gradient(90deg, rgba(0,0,0,0) 0%, ${color.semantic.neutral[900]} 20%, ${color.semantic.neutral[900]} 80%, rgba(0,0,0,0) 100%);`,

    animation: `${animation.fadeIn} 2s ${animation.easing.snappy} forwards`,
    animationDelay: '1s',
    animationFillMode: 'backwards',
    WebkitAnimationFillMode: 'backwards',
  },
  nine: {
    position: 'absolute',
    top: '90%',
    left: 0,
    width: '100%',
    height: '1px',
    background: `linear-gradient(90deg, rgba(0,0,0,0) 0%, ${color.semantic.neutral[925]} 20%, ${color.semantic.neutral[925]} 80%, rgba(0,0,0,0) 100%);`,

    animation: `${animation.fadeIn} 2s ${animation.easing.snappy} forwards`,
    animationDelay: '1s',
    animationFillMode: 'backwards',
    WebkitAnimationFillMode: 'backwards',
  },
});

export const styles = {
  background,
  vertical,
  horizontal,
};
